# version: '3.9'
services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_php_fpm:8.2-fpm-bullseye
    container_name: nds-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
        - ./:/var/www
        - ./_php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mkassets_docker_network

  # Nginx Service behing reverse proxy
  # see: https://github.com/nginx-proxy/acme-companion?tab=readme-ov-file
  webserver:
    image: nginx:alpine
    container_name: nds-webserver
    restart: unless-stopped
    tty: true
    environment:
      - VIRTUAL_HOST=nds.mkassets.sk
      - LETSENCRYPT_HOST=nds.mkassets.sk
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mkassets_docker_network

  #Ppstgres Service
  db:
    image: postgres:16
    container_name: nds-postgres
    restart: unless-stopped
    env_file:
      - .env.docker-compose
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data
    networks:
      - mkassets_docker_network

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: nds-pgadmin
    restart: unless-stopped
    env_file:
      - .env.docker-compose
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      VIRTUAL_HOST: adminer-nds.mkassets.sk
      LETSENCRYPT_HOST: adminer-nds.mkassets.sk
    ports:
      - "5434:80"
    volumes:
      - ./_pgadmin_data:/var/lib/pgadmin
    networks:
      - mkassets_docker_network

#Docker Networks
networks:
  mkassets_docker_network:
    external: true

volumes:
  _postgres_data:
  _pgadmin_data: