# version: '3.9'
services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_php_fpm:8.2-fpm-bullseye
    # user: "${UID}:${GID}"
    # image: digitalocean.com/php
    container_name: nds-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
        - ./:/var/www
        - ./_php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mkassets_docker_network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nds-webserver
    restart: unless-stopped
    tty: true
    environment:
      - VIRTUAL_HOST=nds.mkassets.sk
      - LETSENCRYPT_HOST=nds.mkassets.sk
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # - /etc/letsencrypt/live/nds.mkassets.sk:/etc/letsencrypt/live/nds.mkassets.sk
      # - /etc/letsencrypt/archive/nds.mkassets.sk:/etc/letsencrypt/archive/nds.mkassets.sk:ro
      # - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
    networks:
      - mkassets_docker_network

  #MySQL Service
  db:
    image: postgres:16
    container_name: nds-postgres
    restart: unless-stopped
    env_file:
      - .env.docker-compose
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data
    networks:
      - mkassets_docker_network

#Docker Networks
networks:
  mkassets_docker_network:
    external: true

volumes:
  _postgres_data: